#!/bin/bash

if (source venv/bin/activate) ; then
		echo "venv installed 👍"
else 
		python3 -m venv venv 
		source venv/bin/activate
		pip install -r requirements.txt
		cd ..
fi

python3 -m mkdocs serve
